# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Govatar < Formula
  desc "GOvatar is an avatar generation library written in GO"
  homepage "https://github.com/o1egl/govatar"
  version "0.4.1"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/o1egl/govatar/releases/download/v0.4.1/darwin-amd64-govatar.tar.gz"
    sha256 "cd3168a3009bf0ccf1c6fbc1fb899884c08c1c23902f83c624520015f937f767"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/o1egl/govatar/releases/download/v0.4.1/darwin-arm64-govatar.tar.gz"
    sha256 "ad4bd8110b7d15ef3cc2e6c348fd54118d8d36801a0528a1c9a6559c25262f7f"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/o1egl/govatar/releases/download/v0.4.1/linux-amd64-govatar.tar.gz"
    sha256 "a286c4d61ff27cfbc08c85a388d9410171b170a856db059476347c3f0caca403"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/o1egl/govatar/releases/download/v0.4.1/linux-armv6-govatar.tar.gz"
    sha256 "94d8e2b6f3cb6c452edf4751f55c2b3afc850e156e05a7c4c561bb7544d158e5"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/o1egl/govatar/releases/download/v0.4.1/linux-arm64-govatar.tar.gz"
    sha256 "4752c265343434376e751c7bdd49825007aa93d77f8db453e6544438096bb899"
  end

  def install
    bin.install "govatar"
  end
end
